server:
  port: 9003

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka

spring:
  application:
    name: demo-login
  resources:
    static-locations: classpath:/templates/


  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&useSSL=false&autoReconnect=true
    driver-class-name: com.mysql.jdbc.Driver


  #  redis:
  #    host: 127.0.0.1
  #    password: redispassword
  #    port: 6379
  #    jedis:
  #      pool:
  #        min-idle: 0
  #        max-active: 8
  #        max-idle: 8
  #    database: 0
  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML5
    suffix: .html
  redis:
    password: pass
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8


#mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.sqc95111.demologin.model.DTO
  #  typeEnumsPackage: cnzsqh.supplychain.*.po.enums
  global-config:
    #刷新mapper 调试神器
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: auto
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: h2
    refresh: true
      #自定义填充策略接口实现
      #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  level:
    root: info
    com:
      ibatis: trace
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.sqc95111.demologin.model.DTO